---
- hosts: all
  become: true
  roles:
    - base

- hosts: redis
  become: true
  gather_facts: False
  vars_files:
    - group_vars/all.yml
    
  roles:
    - redis

- hosts: postgres
  become: true
  gather_facts: False
  vars_files:
    - group_vars/all.yml

  roles:
    - postgresql

- hosts: poll
  become: true
  roles:
    - poll

- hosts: worker
  become: true
  vars_files:
    - group_vars/all.yml
  
  roles:
    - worker

- hosts: result
  become: true
  vars_files:
    - group_vars/all.yml
  
  roles:
    - result

      